nome = str(input('Nome: '))
idade = int(input('Idade: '))
email = str(input('E-mail: '))
telefone = str(input('Telefone[(XX) X.XXXX-XXXX]: '))
telefone = int(input('Telefone: '))
print(nome, idade, email, telefone)
print(nome,"\n", idade,"\n", email,"\n", telefone)